"""empty message

Revision ID: 1973740b5aa8
Revises: e14926990fcb
Create Date: 2020-02-29 19:32:54.349764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1973740b5aa8'
down_revision = 'e14926990fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.drop_column('shows', 'time')
    op.drop_column('shows', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('shows', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('shows', 'datetime')
    # ### end Alembic commands ###
