"""empty message

Revision ID: 6dd2b97f8f02
Revises: 1d1fdb82798a
Create Date: 2020-03-05 15:14:22.076461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd2b97f8f02'
down_revision = '1d1fdb82798a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('show_lists', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'show_lists')
    # ### end Alembic commands ###
