"""empty message

Revision ID: d1673b2d6f83
Revises: 61461c8da443
Create Date: 2020-03-05 18:14:46.651335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1673b2d6f83'
down_revision = '61461c8da443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'past_shows')
    op.drop_column('artists', 'upcoming_shows_count')
    op.drop_column('artists', 'upcoming_shows')
    op.drop_column('artists', 'past_shows_count')
    op.drop_column('venues', 'past_shows')
    op.drop_column('venues', 'upcoming_shows_count')
    op.drop_column('venues', 'upcoming_shows')
    op.drop_column('venues', 'past_shows_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('upcoming_shows', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('past_shows', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('upcoming_shows', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('past_shows', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
