"""empty message

Revision ID: f3f1aa94c0a2
Revises: 253d965e1170
Create Date: 2020-02-29 18:59:38.039183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f1aa94c0a2'
down_revision = '253d965e1170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_link', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('happened', sa.Boolean(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['artist'], ['artists.name'], ),
    sa.ForeignKeyConstraint(['venue'], ['venues.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows')
    # ### end Alembic commands ###
